name: cagt
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.1
  - numpy=1.23.4
  - pip=23.1.2
  - pip:
    - einops==0.4.1
    - h5py==3.6.0
    - imath==0.0.2
    - matplotlib==3.6.2
    - tensorboard==2.10.0
    - opencv_python==4.6.0.66
    - Pillow==9.4.0
    - PyYAML==6.0
    - tqdm==4.64.0
    - nvitop==1.1.2
    - open3d==0.13 
    - OpenEXR==1.3.2
    - timm==0.4.12
    - triton==2.0.0
    - scikit-learn==1.3.2
